-- MySQL Script generated by MySQL Workbench
-- 01/12/15 14:03:54
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `C_AccountNumber` BIGINT UNSIGNED NULL,
  `C_AccountType` VARCHAR(45) NULL,
  `C_FirstName` VARCHAR(45) NULL,
  `C_LastName` VARCHAR(45) NULL,
  `C_MidName` VARCHAR(45) NULL,
  `C_IDNumber` VARCHAR(45) NULL,
  `C_Phone1` INT NULL,
  `C_Phone2` INT NULL,
  `C_Address1` VARCHAR(100) NULL,
  `C_Address2` VARCHAR(100) NULL,
  `C_Email` VARCHAR(45) NULL,
  `C_State` VARCHAR(45) NULL,
  `C_ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`C_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InterestRate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InterestRate` (
  `I_ID` INT NOT NULL,
  `I_SavingAccoutType` VARCHAR(45) NULL,
  `I_InterestRate` VARCHAR(45) NULL,
  `I_Currency` VARCHAR(45) NULL,
  PRIMARY KEY (`I_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SavingAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SavingAccount` (
  `S_ID` INT NOT NULL AUTO_INCREMENT,
  `C_ID` INT NULL,
  `S_BalanceAmount` MEDIUMTEXT NULL,
  `S_Repeatable` INT NULL,
  `I_ID` INT NOT NULL,
  PRIMARY KEY (`S_ID`, `I_ID`),
  INDEX `fk_SavingAccount_InterestRate_idx` (`I_ID` ASC),
  CONSTRAINT `fk_SavingAccount_InterestRate`
    FOREIGN KEY (`I_ID`)
    REFERENCES `mydb`.`InterestRate` (`I_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SavingAccount_Customer1`
    FOREIGN KEY (`S_ID`)
    REFERENCES `mydb`.`Customer` (`C_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `T_ID` INT NOT NULL,
  `T_Amount` MEDIUMTEXT NULL,
  `T_DateStart` DATE NULL,
  `T_DateEnd` DATE NULL,
  `SavingAccount_S_ID` INT NOT NULL,
  PRIMARY KEY (`T_ID`, `SavingAccount_S_ID`),
  CONSTRAINT `fk_Transaction_SavingAccount1`
    FOREIGN KEY (`T_ID`)
    REFERENCES `mydb`.`SavingAccount` (`S_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `U_ID` INT NOT NULL AUTO_INCREMENT,
  `U_UserName` VARCHAR(45) NULL,
  `U_Password` VARCHAR(45) NULL,
  `U_Role` VARCHAR(45) NULL,
  PRIMARY KEY (`U_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction_has_User` (
  `Transaction_T_ID` INT NOT NULL,
  `Transaction_SavingAccount_S_ID` INT NOT NULL,
  `User_U_ID` INT NOT NULL,
  PRIMARY KEY (`Transaction_T_ID`, `Transaction_SavingAccount_S_ID`, `User_U_ID`),
  INDEX `fk_Transaction_has_User_User1_idx` (`User_U_ID` ASC),
  INDEX `fk_Transaction_has_User_Transaction1_idx` (`Transaction_T_ID` ASC, `Transaction_SavingAccount_S_ID` ASC),
  CONSTRAINT `fk_Transaction_has_User_Transaction1`
    FOREIGN KEY (`Transaction_T_ID` , `Transaction_SavingAccount_S_ID`)
    REFERENCES `mydb`.`Transaction` (`T_ID` , `SavingAccount_S_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_has_User_User1`
    FOREIGN KEY (`User_U_ID`)
    REFERENCES `mydb`.`User` (`U_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Transaction` (
  `User_U_ID` INT NOT NULL,
  `Transaction_T_ID` INT NOT NULL,
  `Transaction_SavingAccount_S_ID` INT NOT NULL,
  `Transaction_User_U_ID` INT NOT NULL,
  PRIMARY KEY (`User_U_ID`, `Transaction_T_ID`, `Transaction_SavingAccount_S_ID`, `Transaction_User_U_ID`),
  INDEX `fk_User_has_Transaction_Transaction1_idx` (`Transaction_T_ID` ASC, `Transaction_SavingAccount_S_ID` ASC, `Transaction_User_U_ID` ASC),
  INDEX `fk_User_has_Transaction_User1_idx` (`User_U_ID` ASC),
  CONSTRAINT `fk_User_has_Transaction_User1`
    FOREIGN KEY (`User_U_ID`)
    REFERENCES `mydb`.`User` (`U_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Transaction_Transaction1`
    FOREIGN KEY (`Transaction_T_ID` , `Transaction_SavingAccount_S_ID`)
    REFERENCES `mydb`.`Transaction` (`T_ID` , `SavingAccount_S_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction_has_TransactionUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction_has_TransactionUser` (
  `Transaction_T_ID` INT NOT NULL,
  `Transaction_SavingAccount_S_ID` INT NOT NULL,
  `TransactionUser_TU_ID` INT NOT NULL,
  PRIMARY KEY (`Transaction_T_ID`, `Transaction_SavingAccount_S_ID`, `TransactionUser_TU_ID`),
  INDEX `fk_Transaction_has_TransactionUser_TransactionUser1_idx` (`TransactionUser_TU_ID` ASC),
  INDEX `fk_Transaction_has_TransactionUser_Transaction1_idx` (`Transaction_T_ID` ASC, `Transaction_SavingAccount_S_ID` ASC),
  CONSTRAINT `fk_Transaction_has_TransactionUser_Transaction1`
    FOREIGN KEY (`Transaction_T_ID` , `Transaction_SavingAccount_S_ID`)
    REFERENCES `mydb`.`Transaction` (`T_ID` , `SavingAccount_S_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_has_TransactionUser_TransactionUser1`
    FOREIGN KEY (`TransactionUser_TU_ID`)
    REFERENCES `mydb`.`TransactionUser` (`TU_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransactionUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TransactionUser` (
  `User_U_ID` INT NOT NULL,
  `TU_ID` INT NOT NULL AUTO_INCREMENT,
  `Transaction_T_ID` INT NOT NULL,
  `Transaction_SavingAccount_S_ID` INT NOT NULL,
  PRIMARY KEY (`TU_ID`, `User_U_ID`, `Transaction_T_ID`, `Transaction_SavingAccount_S_ID`),
  INDEX `fk_Transaction_has_User1_User1_idx` (`User_U_ID` ASC),
  INDEX `fk_TransactionUser_Transaction1_idx` (`Transaction_T_ID` ASC, `Transaction_SavingAccount_S_ID` ASC),
  CONSTRAINT `fk_Transaction_has_User1_User1`
    FOREIGN KEY (`User_U_ID`)
    REFERENCES `mydb`.`User` (`U_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TransactionUser_Transaction1`
    FOREIGN KEY (`Transaction_T_ID` , `Transaction_SavingAccount_S_ID`)
    REFERENCES `mydb`.`Transaction` (`T_ID` , `SavingAccount_S_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
